SELECT * 
FROM [dbo].[CovidDeaths]
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

SELECT * 
FROM [dbo].[CovidVaccinations]
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4


SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM [dbo].[CovidDeaths]
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

-- LOOKING AT TOTAL CASES VS TOTAL DEATHS
-- SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY
SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS PERCENTPOPULATIONINFECTED
FROM [dbo].[CovidDeaths]
WHERE LOCATION LIKE '%PHILIPPINES%'
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

-- LOOKING AT TOTAL CASES VS POPULATION
-- SHOWS WHAT PERCENTAGE OF POPULATION GOT COVID
SELECT LOCATION, DATE, POPULATION, TOTAL_CASES, (TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED
FROM [dbo].[CovidDeaths]
WHERE LOCATION LIKE '%PHILIPPINES%'
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

-- LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION
SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, MAX((TOTAL_CASES/POPULATION))*100 AS PERCENTPOPULATIONINFECTED
FROM [dbo].[CovidDeaths]
--WHERE LOCATION LIKE '%PHILIPPINES%'
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC

-- SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION
SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS int)) AS TOTALDEATHCOUNT
FROM [dbo].[CovidDeaths]
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC 

-- LET'S BREAK THINGS DOWN BY CONTINENT


-- SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION
SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS int)) AS TOTALDEATHCOUNT
FROM [dbo].[CovidDeaths]
WHERE continent IS NOT NULL
GROUP BY continent
ORDER BY TOTALDEATHCOUNT DESC 

-- GLOBAL NUMBERS
SELECT SUM(NEW_CASES) AS TOTALCASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTALDEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM [dbo].[CovidDeaths]
WHERE continent IS NOT NULL
ORDER BY 1,2


-- LOOKING AT TOTAL POPULATION VS VACCINATIONS
SELECT DEA.continent, DEA.LOCATION, DEA.DATE, DEA.population, VAC.new_vaccinations
FROM [dbo].[CovidDeaths] DEA
JOIN [dbo].[CovidVaccinations] VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.continent IS NOT NULL
ORDER BY 2,3

-- USE CTE
WITH POPSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED)
AS 
(
SELECT DEA.continent, DEA.LOCATION, DEA.DATE, DEA.population, VAC.new_vaccinations
, SUM(CAST(VAC.NEW_VACCINATIONS AS numeric)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS ROLLINGPEOPLEVACCINATED 
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [dbo].[CovidDeaths] DEA
JOIN [dbo].[CovidVaccinations] VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.continent IS NOT NULL
-- ORDER BY 2,3
)
SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM POPSVAC


-- TEMP TABLE
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGPEOPLEVACCINATED NUMERIC
)
INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT DEA.continent, DEA.LOCATION, DEA.DATE, DEA.population, VAC.new_vaccinations
, SUM(CAST(VAC.NEW_VACCINATIONS AS numeric)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS ROLLINGPEOPLEVACCINATED 
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [dbo].[CovidDeaths] DEA
JOIN [dbo].[CovidVaccinations] VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
-- WHERE DEA.continent IS NOT NULL
-- ORDER BY 2,3

SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM #PERCENTPOPULATIONVACCINATED

-- CREATING VIEW TO STORE DATA LATER FOR VISUALIZATIONS
CREATE VIEW PERCENTPOPULATIONVACCINATED AS 
SELECT DEA.continent, DEA.LOCATION, DEA.DATE, DEA.population, VAC.new_vaccinations
, SUM(CAST(VAC.NEW_VACCINATIONS AS numeric)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
AS ROLLINGPEOPLEVACCINATED 
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [dbo].[CovidDeaths] DEA
JOIN [dbo].[CovidVaccinations] VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.continent IS NOT NULL
-- ORDER BY 2,3

SELECT *
FROM PERCENTPOPULATIONVACCINATED